### REF: https://github.com/pypa/gh-action-pypi-publish
### Use official GitHub Action only

name: build wheel and upload to PyPI

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build_wheel:
    name: Build wheel file
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Fetch full history and tags

      - uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - name: Build wheel
        run: |
          pip install build
          python -m build --wheel

      - name: Upload wheel to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        # with:
          # To test: repository-url: https://test.pypi.org/legacy/
          # path: dist/