### REF: https://github.com/pypa/gh-action-pypi-publish
### https://github.com/pypa/cibuildwheel/blob/main/examples/github-deploy.yml
### This action upload the wheel to PyPI after the build_wheel.yml is built successfully

name: upload_wheel_to_PyPI

on:
  # push:
  #   branches: [main, dev]

  workflow_run:
    workflows: ["build_wheel_purepython"]   # The exact name of the other workflow (not file name)
    types:
      - completed                  # Run only after it finishes

jobs:
  upload_pypi:
    name: Upload to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    # if: github.event_name == 'release' && github.event.action == 'published'
    # if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/tags/dev') || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev')

    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # run only if successful

    steps:
      - uses: actions/checkout@v4

      - uses: pypa/gh-action-pypi-publish@release/v1
        # with:
          # To test: repository-url: https://test.pypi.org/legacy/
          # path: dist/